### ISSUE TITLE
would you please provide the curriculum slides?

### ISSUE THREAD

**Issue by xingyeyouran** [bwhyman/springboot-course#1]
Existing files on mooc is incomplete. The overlaps of prictures are shadowed and we can't such parts.

**Comment by bwhyman** [comment]
Although the version of the technical framework is being updated, but the principle remains the same, so the teaching is directly based on the `programming code` not the slide. Therefore, the slides are no longer updated in time.
The current teaching technologies (May, 2023) will be migrated to Reactive Programming, and there are no more documents yet. However, you can find many similar tutorials online.
springboot 3.0+spring-webflux+spring-data-reactive-jdbc

**Comment by xingyeyouran** [comment]
Thank You!
