### ISSUE TITLE
file EncryptComponent05.java may need beark the circular reference.

### ISSUE THREAD

**Issue by xingyeyouran** [bwhyman/springboot-course#2]
the file[***EncryptComponent05.java***](https://github.com/bwhyman/springboot-course/blob/master/springmvc-examples/src/main/java/com/example/springmvcexamples/example05/textencryptor/EncryptComponent05.java) its self is a `@Component` and there is a `@Autowired`  virable which is initialized below.  Actually, when I do this, I found that spring initialize failed with the information **"spring admit Is there an unresolvable circular reference"**.
So I think there needs a `@Lazy` Annotation upper code: the private TextEncryptor encryptor; or other ways to break circular reference.

**Comment by bwhyman** [comment]
1. This file is created two years ago and spring has no longer recommended @Autowired. Try this

```java
    private final ObjectMapper objectMapper;
    @Value("${my.secretkey}")
    private String secretKey;
    @Value("${my.salt}")
    private String salt;
    private TextEncryptor encryptor;

    public EncryptComponent05(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @PostConstruct
    public void getTextEncryptor() {
        encryptor = Encryptors.text(secretKey, salt);
    }
```
2.  My custom encryption component is not a standard like JWT, so it's hard to break. Howover, JWT is more widely used.

**Comment by bwhyman** [comment]
Are you one of my students?

**Comment by xingyeyouran** [comment]
> Are you one of my students?

Yes. I am your student in Class 2017. Recently I have been preparing to find an internship, so I begin to review JAVA Spring.

**Comment by bwhyman** [comment]
> > Are you one of my students?
> 
> Yes. I am your student in Class 2017. Recently I have been preparing to find an internship, so I begin to review JAVA Spring.

Oh, yes. Postgraduate students are about to graduate. Time flies over both of us....
Try spring-reactive framework told you before.
/bwhyman/mentor-selection

**Comment by bwhyman** [comment]
> > Are you one of my students?
> 
> Yes. I am your student in Class 2017. Recently I have been preparing to find an internship, so I begin to review JAVA Spring.

Oh, yes. Postgraduate students are about to graduate. Time flies over both of us....
Try spring-reactive framework told you before.
/bwhyman/mentor-selection

**Comment by xingyeyouran** [comment]
> 
Ok, I will study it soon.
Thank you for your consistently guiding, no matter past or now.
Please accept my deepest gratitude.

**Comment by bwhyman** [comment]
Work hard together. :fire:
